version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - pip install -r requirements.txt

  pre_build:
    commands:
      - echo Running tests...
      - pytest
      - echo Tests finalized...
  build:
    commands:
      - echo Build started on `date`
      - echo Building the FastAPI application...
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
  base-directory: '/'
